### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by jmcrey** [Flatline720/intro-data-capstone-biodiversity#1]
### Criteria 1: Presentation / Analysis Document
* _Score Level:_ 3 (Meets Expectations)
* _Comment(s):_ Firstly, let me just say that I thoroughly enjoyed the Prezzi presentation! It was very creative! The only thing the presentation is missing is a recommendation/conclusion slide. As a whole, the presentation does a good job outlining every step taken to analyze the data, but it does not provide a centralized recommendations or conclusions slide based off of all the analysis. These slides help summarize the analysis done and why that analysis is important. Effectively, it provides the reader their key-takeaways from the analysis. Besides that, nice job with this presentation!
 
### Criteria 2: Code Accuracy
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ All the code accurately retrieves the intended data, leverages the custom libraries to analyze the data, and displays the data in a friendly format. Further, the code is well formatted and easy to read. Great job with the code!
 
### Criteria 3: Understanding Hypothesis Testing and Interpreting the P-Value
* _Score Level:_ 3 (Meets Expectations)
* _Comment(s):_ In each of the hypothesis testing, the hypothesis was stated, the testing was correctly conducted, and it was stated whether or not there was statistically significant difference based off the tests results. The only thing that this slide was lacking is an interpretation of the outcome of the testing: it was stated there was a significant difference based on the Chi 2 test, but the document does not re-interpret the hypothesis based off these results. For example, it may help to explicitly state whether the hypothesis is accepted or rejected, then rephrasing the hypothesis so that the reader can truly understand the impact of the test. Besides this, the hypothesis testing slides were well done! 
 
### Criteria 4: Ability to Interpret the Objective & Outcome of the Analysis in a Business Context
* _Score Level:_ 2 (Approaches Expectations)
* _Comment(s):_ Although there seems to be a stated objective for the presentation, there was no summary slide showing all the findings from the data analysis. There were some insights drawn throughout the presentation, but they were not succinctly summarized so that the reader knew exactly what they were taking from the presentation. 

### Overall Score: 12/16

Overall, this was a very good project! I truly enjoyed the presentation and I loved how it walked the reader through every step taken to analyze the data. The biggest thing that could have improved the presentation is a recommendation/conclusion slide that succinctly summarized all insights drawn from the analysis. A recommendation / conclusion slide is quintessential for a reader because it shows exactly what they should be taking away from the data analysis. In other words, it simply summarizes all the insights drawn from the data analytics and provides the reader the key takeaways so that they can be used by the reader! 

Besides the recommendation/conclusion slide, everything else was spot-on: the code was well-formatted and accurate, the presentation showed every step taken, and the hypothesis testing was done well. So, very nice job with this project!

**Comment by TBKHori** [comment]
Thank you. I will work on better presentation of conclusions, derived from the project and more explanation of the analysis tests conducted.

**Comment by TBKHori** [comment]
The project was an Amazing experience and the review will be heeded.I look forward to working with companies in accordance with the skills i have gained.
